packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    deps:
      - components/ws-manager-bridge-api/go:lib
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      packaging: app
