packages:
  - name: app
    type: go
    deps:
      - components/common-go:lib
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      packaging: app
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/kubelet-config-fix:${version}
